import Head from 'next/head';
import IcomoonReact from "icomoon-react";
import iconSet from "../icons/selection.json";
import NavBar from '@/components/organisms/NavBar';
import Profile from '../organisms/Profile';
import styles from '@/styles/Contact.module.css';

export default function Contact() {

    return (
        <>
            <Head>
                <title>Contact - Jordan Morrison Photography</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className={styles.contact}>
            
                <h4>Contact Info</h4>
                <p>Feel free to send me an email at the address below and I'll get back to you as soon as possible. I'm also available for messages on Instagram & TikTok.</p>
                <a href='mailto:jordanmorrison.photos@gmail.com'>jordanmorrison.photos@gmail.com</a>
                <div className={styles.socials}>
                    <a href="https://www.instagram.com/morrison_jordan/" target='_blank'>
                        <IcomoonReact iconSet={iconSet} size={16} icon="instagram"/>
                    </a>
                    <a href="https://www.tiktok.com/@morrison.jordan" target='_blank'>
                        <IcomoonReact iconSet={iconSet} size={16} icon="tiktok"/>
                    </a>
                </div>
            </div>
        </>
    )
}