import { useState, useEffect } from 'react';
import Head from 'next/head';
import NavBar from '@/components/organisms/NavBar';
import Tabs from '../organisms/Tabs';
import PhotoGrid from '../organisms/PhotoGrid';
import categories from '@/data/categories.json';
import styles from '@/styles/Home.module.css';

export default function Home(props) {

    const [activeTab, setActiveTab] = useState(props.category);

    const handleTabChange = (category) => {
        setActiveTab(category);
    };

    return (
        <>
            <Head>
                <title>Jordan Morrison</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                <NavBar/>
                <h1>Jordan Morrison</h1>
                {activeTab &&
                    <>
                        <Tabs tabs={categories} activeTab={activeTab} onTabClick={handleTabChange}/>
                        <PhotoGrid images={props.images}/>
                    </>
                }
        </>
    )
}