import { useState, useEffect } from 'react';
import Head from 'next/head';
import NavBar from '@/components/organisms/NavBar';
import Tabs from '../organisms/Tabs';
import PhotoGrid from '../organisms/PhotoGrid';
import styles from '@/styles/Home.module.css';

export default function Home() {

    const [activeTab, setActiveTab] = useState(null);

    useEffect(() => {
        let hash = decodeURI(window.location.hash.substring(1));
        setActiveTab(hash ? hash : "adventure");
    },[]);

    const handleTabChange = (ev) => {
        setActiveTab(ev.target.innerText.toLowerCase());
        window.history.replaceState(null, null, `/#${encodeURI(ev.target.innerText.toLowerCase())}`);
    };

    return (
        <>
            <Head>
                <title>Jordan Morrison</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                <NavBar/>
                <h1>Jordan Morrison</h1>
                {activeTab &&
                    <>
                        <Tabs tabs={["Adventure", "Real Estate", "Product"]} activeTab={activeTab} onTabClick={handleTabChange}/>
                        <PhotoGrid/>
                    </>
                }
        </>
    )
}