import Head from 'next/head';
import NavBar from '@/components/organisms/NavBar';
import PhotoGrid from '../organisms/PhotoGrid';
// import NavBar from '@/components/organisms/NavBar';
// import CardGrid from '../organisms/CardGrid';
// import Footer from '../organisms/Footer';
// import Typewriter from 'typewriter-effect';
// import { useInView } from 'react-intersection-observer';
// import work from '@/Data/work.json';
import styles from '@/styles/Home.module.css';

export default function Home() {

    return (
        <>
            <Head>
                <title>Jordan Morrison</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                <NavBar/>
                <PhotoGrid/>
        </>
    )
}